/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xwing;

/**
 *
 * @author Michael
 */
public class MainGameplayPanel extends javax.swing.JPanel {


    /**
     * Creates new form MainGameplayPanel
     */
    public MainGameplayPanel () {
        initComponents();
        
        this.shipList1.form = shipForm1;
        this.gameMap1.l = shipList1;
    }


    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainDisplayPanel = new javax.swing.JPanel();
        manueverDial1 = new xwing.ManueverDial();
        jButton1 = new javax.swing.JButton();
        gameMap1 = new xwing.GameMap();
        shipList1 = new xwing.ShipList();
        shipForm1 = new xwing.ShipForm();

        jButton1.setText("Start");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout manueverDial1Layout = new javax.swing.GroupLayout(manueverDial1);
        manueverDial1.setLayout(manueverDial1Layout);
        manueverDial1Layout.setHorizontalGroup(
            manueverDial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        manueverDial1Layout.setVerticalGroup(
            manueverDial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manueverDial1Layout.createSequentialGroup()
                .addGap(0, 261, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        gameMap1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gameMap1.setPreferredSize(new java.awt.Dimension(914, 914));

        javax.swing.GroupLayout gameMap1Layout = new javax.swing.GroupLayout(gameMap1);
        gameMap1.setLayout(gameMap1Layout);
        gameMap1Layout.setHorizontalGroup(
            gameMap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        gameMap1Layout.setVerticalGroup(
            gameMap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );

        shipList1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        shipForm1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout MainDisplayPanelLayout = new javax.swing.GroupLayout(MainDisplayPanel);
        MainDisplayPanel.setLayout(MainDisplayPanelLayout);
        MainDisplayPanelLayout.setHorizontalGroup(
            MainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameMap1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shipForm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shipList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manueverDial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainDisplayPanelLayout.setVerticalGroup(
            MainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainDisplayPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(shipList1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shipForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manueverDial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainDisplayPanelLayout.createSequentialGroup()
                        .addComponent(gameMap1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        GameManager.curPhase = GameManager.GamePhase.Movement;
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainDisplayPanel;
    private xwing.GameMap gameMap1;
    private javax.swing.JButton jButton1;
    private xwing.ManueverDial manueverDial1;
    private xwing.ShipForm shipForm1;
    private xwing.ShipList shipList1;
    // End of variables declaration//GEN-END:variables
}
