/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xwing;

import java.awt.Graphics;

/**
 *
 * @author Michael
 */
public class MainGameplayPanel extends javax.swing.JPanel implements Refreshable {

    private boolean wasVisible = false;

    /**
     * Creates new form MainGameplayPanel
     */
    public MainGameplayPanel () {
        initComponents();
        
    }


    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainDisplayPanel = new javax.swing.JPanel();
        manueverDial1 = new xwing.ManueverDial();
        gameMap1 = new xwing.GameMap();
        shipList1 = new xwing.ShipList();
        shipForm1 = new xwing.ShipForm();

        javax.swing.GroupLayout manueverDial1Layout = new javax.swing.GroupLayout(manueverDial1);
        manueverDial1.setLayout(manueverDial1Layout);
        manueverDial1Layout.setHorizontalGroup(
            manueverDial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        manueverDial1Layout.setVerticalGroup(
            manueverDial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        gameMap1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gameMap1.setPreferredSize(new java.awt.Dimension(914, 914));

        javax.swing.GroupLayout gameMap1Layout = new javax.swing.GroupLayout(gameMap1);
        gameMap1.setLayout(gameMap1Layout);
        gameMap1Layout.setHorizontalGroup(
            gameMap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        gameMap1Layout.setVerticalGroup(
            gameMap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );

        shipList1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        shipForm1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout MainDisplayPanelLayout = new javax.swing.GroupLayout(MainDisplayPanel);
        MainDisplayPanel.setLayout(MainDisplayPanelLayout);
        MainDisplayPanelLayout.setHorizontalGroup(
            MainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameMap1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shipForm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shipList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manueverDial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainDisplayPanelLayout.setVerticalGroup(
            MainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainDisplayPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(MainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainDisplayPanelLayout.createSequentialGroup()
                        .addComponent(gameMap1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MainDisplayPanelLayout.createSequentialGroup()
                        .addComponent(shipList1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shipForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manueverDial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainDisplayPanel;
    private xwing.GameMap gameMap1;
    private xwing.ManueverDial manueverDial1;
    private xwing.ShipForm shipForm1;
    private xwing.ShipList shipList1;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void refresh() {
        
        if(GameManager.squadChanged) {
            
            shipList1.loadList();
            GameManager.squadChanged = false;
        }
        
        if(shipList1.selectionChanged) {
            Ship selected = shipList1.getSelectedShip();
            if(selected != null) {
                shipForm1.loadShip(selected);
            }
            shipList1.selectionChanged = false;
        }
       
        this.gameMap1.repaint();

    }
}
