/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xwing;


import javax.swing.DefaultListModel;



/**
 *
 * @author Michael
 */
public class ShipList extends javax.swing.JPanel {

    int tempSelectedIndex = -1;
    int selectedIndex = -1;
    int selectedTeam = 0;
    
    boolean selectionChanged;
 
    
    ShipForm form;

    /**
     * Creates new form ShipList
     */
    public ShipList () {
        initComponents();
        loadList();
        
    }
    
    /**
     *
     * @param i
     */
    public void setSelectedIndex(int i) {
        
        playerSquad.setSelectedIndex(i);
        
    }
    
    
    /** Loads the ships from GameManager into the JLists
     *
     */
    public void loadList() {
        
        tempSelectedIndex = playerSquad.getSelectedIndex();
        
        DefaultListModel playerList = new DefaultListModel();
        this.playerSquad.setModel(playerList);
        
        DefaultListModel opponentList = new DefaultListModel();
        this.opponenetSquad.setModel(opponentList);
        
        playerList.clear();
        opponentList.clear();
        
        for(Ship s: GameManager.playerSquadron) {
            playerList.addElement(s.pilot.getPilotName());
        }
        for(Ship s: GameManager.opponentSquadron) {
            opponentList.addElement(s.pilot.getPilotName());
        }
        playerSquad.setSelectedIndex(tempSelectedIndex);
        tempSelectedIndex = -1;
        
    }


    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        playerSquad = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        opponenetSquad = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();

        playerSquad.setModel(new javax.swing.DefaultListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        playerSquad.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                playerSquadValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(playerSquad);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Player Squad");

        opponenetSquad.setModel(new javax.swing.DefaultListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        opponenetSquad.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                opponenetSquadValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(opponenetSquad);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Opponent Squad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public Ship getSelectedShip() {
        if(selectedIndex < 0)
            return null;
        
        if (selectedTeam ==0) {
            return GameManager.playerSquadron.get(selectedIndex);
        } else if (selectedTeam == 1) {
            return GameManager.opponentSquadron.get(selectedIndex);
        } else {
            return null;
        }   
    }
    
    
    private void playerSquadValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_playerSquadValueChanged
        System.out.println("Selected PLayer");
        selectionChanged = true;
        selectedTeam = 0;
        selectedIndex = evt.getFirstIndex();                
        opponenetSquad.clearSelection();
    }//GEN-LAST:event_playerSquadValueChanged

    private void opponenetSquadValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_opponenetSquadValueChanged
        System.out.println("Selected OPP");
        selectionChanged = true;
        selectedTeam = 1;
        selectedIndex = evt.getFirstIndex();
        playerSquad.clearSelection();
    }//GEN-LAST:event_opponenetSquadValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList opponenetSquad;
    private javax.swing.JList playerSquad;
    // End of variables declaration//GEN-END:variables
}
