/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xwing;

import java.awt.Component;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;

/**
 *
 * @author Michael
 */
public class XWingGUI extends javax.swing.JFrame implements Refreshable {

    final static int topLayer = 5;
    static GameManager.GamePhase curPhase;
    
    
    /**
     * Creates new form XWingGUI
     */
    public XWingGUI() {

        initComponents();
        initRenderManager(60);
        
    }
    
    public static void showPhase(GameManager.GamePhase phase) {

        if(curPhase != phase) {

            curPhase = phase;
            
            resetMainGui();

            switch(phase) {

                case MainMenu:
                    mainGuiContainer.setLayer(startupMenu,topLayer);
                    startupMenu.setVisible(true);
                    break;
                case SquadBuilding:
                    mainGuiContainer.setLayer(shipBuilderPanel, topLayer);
                    shipBuilderPanel.setVisible(true);
                    break;
                 case SquadPlacement:
                    GameManager.resetShips();
                    mainGuiContainer.setLayer(gameMap, topLayer);
                    gameMap.setVisible(true);
                    break;
                case Movement:
                    mainGuiContainer.setLayer(gameMap, topLayer);
                    gameMap.setVisible(true);
                    break;
                default:

            }    
        }
    }


    public static void resetMainGui() {
        for(Component comp: mainGuiContainer.getComponents()) {
            mainGuiContainer.setLayer(comp, 0);
            //comp.setSize(GuiManager.mainWindow.getWidth(), GuiManager.mainWindow.getHeight());
            comp.setVisible(false);
        }
    }

   
    /**
     * An initialization method used to start the render manager at a target fps
     * @param targetFps the target frame rate. This is the maximum frame rate the
     *                  visual will be rendered at
     */
    private void initRenderManager(int targetFps) {
        long timeDelay = Math.round(1000d/(double)targetFps);
        RenderManager rm = new RenderManager();
        Timer t = new Timer();
        t.scheduleAtFixedRate(rm, 0, timeDelay);
    }

    public static MainGameplayPanel getGameMap() {
        return gameMap;
    }

    public static JLayeredPane getMainGuiContainer() {
        return mainGuiContainer;
    }

    public static MainMenuPanel getStartupMenu() {
        return startupMenu;
    }
    
    public void refresh() {
        
        for(Component comp: mainGuiContainer.getComponentsInLayer(topLayer)) {
            if(comp.isVisible())
                ((Refreshable)comp).refresh();
        }
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainGuiContainer = new javax.swing.JLayeredPane();
        gameMap = new xwing.MainGameplayPanel();
        startupMenu = new xwing.MainMenuPanel();
        shipBuilderPanel = new xwing.ShipBuilderPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gameMap.setBounds(0, 0, 1330, 940);
        mainGuiContainer.add(gameMap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startupMenu.setBounds(0, 0, 1330, 940);
        mainGuiContainer.add(startupMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shipBuilderPanel.setBounds(0, 0, 1340, 950);
        mainGuiContainer.add(shipBuilderPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainGuiContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1337, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainGuiContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XWingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XWingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XWingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XWingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XWingGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static xwing.MainGameplayPanel gameMap;
    private static javax.swing.JLayeredPane mainGuiContainer;
    private static xwing.ShipBuilderPanel shipBuilderPanel;
    private static xwing.MainMenuPanel startupMenu;
    // End of variables declaration//GEN-END:variables
}
